### ISSUE TITLE
Amplitude modulation

### ISSUE THREAD

**Issue by ranibourbara** [Bruce-Evans/ArduinoDueArbitraryWaveformGeneratorAndController#1]
Hi Bruce,

Thank you for this amazing work. Works like charm. 

I am wondering if it is possible to modulate the amplitude of the generated wave. Basically I want to run a wave that fades in and out.

Best,
Rani

**Comment by Bruce-Evans** [comment]
Hi,
Sorry for not seeing your comment earlier.
Modulation is not possible with this program.
Regards,
Bruce.
