### ISSUE TITLE
How can I download the tar.gz file?

### ISSUE THREAD

**Issue by cotampanie** [Bruce-Evans/ArduinoDueArbitraryWaveformGeneratorAndController#2]
Hello,
I would like to download the source code for your program (since I want to run it on a Linux system), but when I click on the download option for the tarball or the zip, all I get is the Readme file.  Please advise.

**Comment by Bruce-Evans** [comment]
Hi,
A Linux version has now been released.
Click on "3 releases" to get at the files.
Sorry for the late reply.
Regards,
Bruce.
