### ISSUE TITLE
Gentle Request for contact

### ISSUE THREAD

**Issue by ghost** [Bruce-Evans/ArduinoDueArbitraryWaveformGeneratorAndController#6]
Hi Bruce, 

Sorry I couldn't find a way to contact you so took the liberty to use this way. Is there are way in which I can contact you by private email for some questions on your Wave Generator please? 

Kind Regards,

**Comment by Bruce-Evans** [comment]
I'd rather not give my private email, but you can ask questions here, or on the Arduino website here: 
https://create.arduino.cc/projecthub/BruceEvans/arduino-due-arbitrary-waveform-generator-a9d180?f=1
