### ISSUE TITLE
The window needs to scale for bigger monitors

### ISSUE THREAD

**Issue by PostDocTC** [Bruce-Evans/ArduinoDueArbitraryWaveformGeneratorAndController#8]
I have a big monitor and the window for the controller is just too small.
![Due_too_Tiny](https://user-images.githubusercontent.com/88821184/187342522-1505cff2-414a-4cf8-b032-68f044024951.jpg)

 I've tried increasing the windows global font size without seeing any improvement.  Can you make it possible to increase the size of the window so it's easier to read?

**Comment by Bruce-Evans** [comment]
Sorry for the delayed answer, I only just noticed your issue.
This program is designed with full HD monitors in mind, and I have no plans to change this.
 I assume your monitor must have a much greater resolution than HD. It will also be difficult for you to draw fine details in the drawing window if the pixels are so small, as each pixel represents one waypoint. I can only suggest that if you can change the screen resolution of your monitor to 1920x1080 (HD) this should help.
